### ISSUE TITLE
Análisis de modelos de "Salidas"

### ISSUE THREAD

**Issue by OrihuelaConde** [EEST1Chivilcoy/BomberosVoluntariosChivilcoy#1]
Analizar los modelos existentes de "Salidas" con la documentación provista y realizar los ajustes pertinentes.

[servicios-especiales_20171010131909.pdf](https://github.com/EEST1Chivilcoy/BomberosVoluntariosChivilcoy/files/11688689/servicios-especiales_20171010131909.pdf)
[rescates_20171010131813.pdf](https://github.com/EEST1Chivilcoy/BomberosVoluntariosChivilcoy/files/11688692/rescates_20171010131813.pdf)
[materiales-peligrosos_20171010131743.pdf](https://github.com/EEST1Chivilcoy/BomberosVoluntariosChivilcoy/files/11688690/materiales-peligrosos_20171010131743.pdf)
[incendios_20171010131656.pdf](https://github.com/EEST1Chivilcoy/BomberosVoluntariosChivilcoy/files/11688693/incendios_20171010131656.pdf)
[factores-climaticos_20171010131613.pdf](https://github.com/EEST1Chivilcoy/BomberosVoluntariosChivilcoy/files/11688694/factores-climaticos_20171010131613.pdf)
[accidente_20171010131529.pdf](https://github.com/EEST1Chivilcoy/BomberosVoluntariosChivilcoy/files/11688691/accidente_20171010131529.pdf)

**Comment by Bernard2806** [comment]
Los modelos de "Salidas" ya están creados y actualizados, incluyendo tanto los definidos en los documentos referenciados como los adicionales identificados mediante el RUBA. Queda pendiente verificar que funcionen correctamente todas las Salidas.
