### ISSUE TITLE
Acomodar el  ABM  Brigadas

### ISSUE THREAD

**Issue by Fefo7** [EEST1Chivilcoy/BomberosVoluntariosChivilcoy#10]

**Comment by Bernard2806** [comment]
Este issue fue marcado como `Done`, pero aun seguimos trabajando algunos detalles de las Brigadas, se ha creado un nuevo issue específico que aborda el tema de las Brigadas. Por lo tanto, procedemos a cerrar este issue.

El nuevo issue puede encontrarse aquí:  #73
