### ISSUE TITLE
Mala visualización (servicios-industrial)

### ISSUE THREAD

**Issue by Priscila343** [EEST1Chivilcoy/BomberosVoluntariosChivilcoy#101]
## Descripción:
la visualización de la pagina esta cortada 

## Pasos para reproducir:
- Ingresar a la página de "Bomberos Voluntarios Chivilcoy".
- Ingresar en la sección "Salidas" y seleccionar "Incendios" del tipo "Industrial".
- Cargar con normalidad la salida.

## Comportamiento esperado:
Los datos deben ser completamente visibles para el usuario

## Comportamiento actual:
la visualización es parcial lo que dificulta la correcta carga de los datos

## Capturas de pantalla o registros:
![Mala visualización 2024-09-05 111646](https://github.com/user-attachments/assets/d60644d7-6c5c-4d0f-ad59-aff8be656805)

**Comment by Bernard2806** [comment]
@FoxZKI Llegaste a Corregir esto?
