### ISSUE TITLE
Palabras Unidas (Reportes-Salidas-Editar)

### ISSUE THREAD

**Issue by Priscila343** [EEST1Chivilcoy/BomberosVoluntariosChivilcoy#105]
## Descripción:
Algunas palabras están unidas y  no cumplen con las reglas de acentuación.

## Pasos para reproducir:
- Ingresar a la página de "Bomberos Voluntarios Chivilcoy".
- Ingresar en la sección "Reportes" y seleccionar "salidas".
- Editar una salida.

## Comportamiento esperado:
Las palabras deberían cumplir las reglas ortográficas y de acentuación.
Todos los datos deben estar especificados 

## Comportamiento actual:
- Algunas de las palabras que se muestran en pantalla están unidas.
- En algunos casos presentan errores de ortografía.
- faltan la descripción de los datos cargados

## Capturas de pantalla o registros:
![historial salida, editar](https://github.com/user-attachments/assets/39ded403-1840-460a-bfc3-f0ba07d1adba)
![falta de datos](https://github.com/user-attachments/assets/bf79c7ad-138e-4af1-883e-0f5a9137f3a2)

## Extra:
-Algunas descripciones de los datos no son visibles.

**Comment by EzeMJaime** [comment]
El acceso a la acción de editar salidas ya no está permitido porque la clase 'EditarSalidas' fue eliminada. Por lo que este issus ya no es relevante, y se necesita crear una nueva clase desde cero para habilitar la edición de salidas nuevamente.
