### ISSUE TITLE
Errores de visualización(Salida-Establecimiento Educativo)

### ISSUE THREAD

**Issue by Priscila343** [EEST1Chivilcoy/BomberosVoluntariosChivilcoy#107]
## Descripción:
Algunas palabras no están centradas en comparación a otras salidas 

## Pasos para reproducir:
- Ingresar a la página de "Bomberos Voluntarios Chivilcoy".
- Ingresar en la sección "Salidas" y seleccionar "Incendio de Establecimiento Educativo".
- Cargar con normalidad la salida.

## Comportamiento esperado:
La página debe tener una interfaz grafica agradable para el usuario.

## Comportamiento actual:
- Algunas de las palabras  no se encuentran centradas comparándolos con las demás salidas 

## Capturas de pantalla o registros:
![Salida escuela](https://github.com/user-attachments/assets/c4fc2ac3-4fee-420b-82db-763ae700d3b1)
![Salida escuela2](https://github.com/user-attachments/assets/3da37d77-ae0f-4f62-a714-87f238bc8e32)
![Salida escuela3](https://github.com/user-attachments/assets/c791abcd-994d-4af5-ba43-c45f20f2cd0f)
![Salida escuela4](https://github.com/user-attachments/assets/2d403280-232e-42fe-962a-5513e1807a11)
![Salida escuela5](https://github.com/user-attachments/assets/145a4e62-1e50-4d61-bdef-0d8f0b48a6db)

## Referencia de otra salidas:
![Referencia](https://github.com/user-attachments/assets/bd5848a8-f2c0-431d-ae9b-b3df824c01fd)

**Comment by Bernard2806** [comment]
Se ha corregido el problema del contenedor descentrado en la salida "Incendio de Establecimiento Educativo". Ahora las palabras están correctamente alineadas y la interfaz es coherente con el diseño de las demás salidas. Verificado y funcionando correctamente.
