### ISSUE TITLE
Errores de visualización(Salida-Comercial)

### ISSUE THREAD

**Issue by Priscila343** [EEST1Chivilcoy/BomberosVoluntariosChivilcoy#108]
## Descripción:
Algunas palabras no están centradas en comparación a otras salidas 

## Pasos para reproducir:
- Ingresar a la página de "Bomberos Voluntarios Chivilcoy".
- Ingresar en la sección "Salidas" y seleccionar "Incendio Comercial".
- Cargar con normalidad la salida.

## Comportamiento esperado:
La página debe tener una interfaz grafica agradable para el usuario.

## Comportamiento actual:
- Algunas de las palabras  no se encuentran centradas comparándolos con las demás salidas 

## Capturas de pantalla o registros:
![Comercial](https://github.com/user-attachments/assets/55dd6d0c-8395-4725-ac44-b924a6afc896)
![Comercial2](https://github.com/user-attachments/assets/ee4bd090-815c-4f29-bd2a-b8092bfbb553)
![Comercial3](https://github.com/user-attachments/assets/fd202646-f89e-4b70-b7d4-9d28446fe959)
![Comercial4](https://github.com/user-attachments/assets/781b3849-2353-4529-995d-53ed87ae8895)
![Comercial5](https://github.com/user-attachments/assets/d80481d6-e157-48e5-b167-66122ea4f3bf)

## Referencia de otra salidas:
![Referencia](https://github.com/user-attachments/assets/bd5848a8-f2c0-431d-ae9b-b3df824c01fd)

**Comment by Bernard2806** [comment]
El contenedor donde se colocan los datos de la salida no estaba centrado correctamente, lo que generaba los problemas de visualización. Ahora se ha ajustado para que esté alineado como el resto de las salidas. Issue cerrado.
