### ISSUE TITLE
Errores de diseño en las salidas de incendios 

### ISSUE THREAD

**Issue by Priscila343** [EEST1Chivilcoy/BomberosVoluntariosChivilcoy#110]
## Descripción:
Algunas de las salidas de incendio tienen imperfectos de diseño.

## Pasos para reproducir:
- Ingresar a la página de "Bomberos Voluntarios Chivilcoy".
- Ingresar en la sección "Salidas" y seleccionar cualquiera de los "Incendios".
- Cargar con normalidad la salida.

## Comportamiento esperado:
-Se debe tener en cuenta que todas las salidas deben ser iguales en diseño 

## Comportamiento actual:
- Las salidas tienen diferencias en sus diseños.

## Capturas de pantalla o registros:
![diseño salidas](https://github.com/user-attachments/assets/7febe767-69ba-4cf1-91c5-2dbbf9fe9673)
![diseño salidas2](https://github.com/user-attachments/assets/7a4b6781-0dc3-4fee-adea-05533000c4ba)

**Comment by Bernard2806** [comment]
Se ha corregido y unificado el diseño de todas las salidas de incendios. Ahora todas las salidas tienen el mismo estilo y los elementos están correctamente centrados para mantener una interfaz gráfica uniforme y agradable para el usuario. Verificado y funcionando como se esperaba.
