### ISSUE TITLE
Se debe crear el apartado ver(Firma-Incidente)

### ISSUE THREAD

**Issue by Priscila343** [EEST1Chivilcoy/BomberosVoluntariosChivilcoy#111]
## Descripción:
En el apartado incidente se debe crear el botón ver para visualizar la descripción del mismo.

## Pasos para reproducir:
- Ingresar a la página de "Bomberos Voluntarios Chivilcoy".
- Ingresar en la sección "Firmas" y seleccionar "Incidentes".

## Comportamiento esperado:
-se debe poder ver la descripción del incidente que tuvo el vehículo

## Comportamiento actual:
- No se pueden ver los incidentes del vehículo 

## Capturas de pantalla o registros:
![Firmas](https://github.com/user-attachments/assets/1cf57038-b7e8-4f1a-806f-abc27b119289)

**Comment by Bernard2806** [comment]
@Priscila343, ¿cuál es el problema con el botón de ver en la sección de incidentes? Según lo mencionado, debería permitir ver la descripción del incidente, pero cuando lo probé, funciona bien. Primero se selecciona el incidente y luego se presiona el botón de ver para mostrar los detalles del incidente del vehículo.
