### ISSUE TITLE
Crear botón de borrar(Firmas-Incidentes)

### ISSUE THREAD

**Issue by Priscila343** [EEST1Chivilcoy/BomberosVoluntariosChivilcoy#112]
## Descripción:
Se debe crear un botón para borrar los incidentes en el apartado de Firmas

## Pasos para reproducir:
- Ingresar a la página de "Bomberos Voluntarios Chivilcoy".
- Ingresar en la sección "Firmas" y seleccionar "Incidentes".

## Comportamiento esperado:
-se debe poder borrar los incidentes en caso de que se cometa un error en la carga de datos
 
## Comportamiento actual:
- No se puede borrar ninguno de los incidentes que tuvo el vehículo en caso de algún error.  

## Capturas de pantalla o registros:
![Firmas](https://github.com/user-attachments/assets/7fa6397f-c0cf-461e-b69c-c2e711563f19)

**Comment by Bernard2806** [comment]
@Priscila343, ¿cuál es el problema con el botón? Lo probé y me funciona bien. Primero se selecciona el incidente y luego se presiona el botón de borrar para eliminar el accidente.

**Comment by Priscila343** [comment]
listo ya lo probé y funciona, no se, la computadora parece no querer funcionar
