### ISSUE TITLE
Modificar el tamaño de todos los apartados

### ISSUE THREAD

**Issue by Priscila343** [EEST1Chivilcoy/BomberosVoluntariosChivilcoy#113]
## Descripción:
Cambiar el tamaño de los apartados para que todos sean iguales. 

## Pasos para reproducir:
- Ingresar a la página de "Bomberos Voluntarios Chivilcoy".

## Comportamiento esperado:
- Todos los apartados deben tener el mismo tamaño. 

## Comportamiento actual:
- Los apartados tienen distinto tamaños.

## Capturas de pantalla o registros:
![cambiar apartados](https://github.com/user-attachments/assets/e210f335-27bc-4e4b-b157-37050f4c6508)

## Extra: 
- se debe alargar el apartado de salidas

**Comment by Bernard2806** [comment]
Este issue será cerrado, ya que actualmente se está trabajando en otro issue relacionado con el rediseño total de la página de inicio, lo cual incluye la estandarización de los tamaños de los apartados. Cualquier ajuste relacionado se abordará en el nuevo diseño.
