### ISSUE TITLE
Datos irrelevantes(Salidas)

### ISSUE THREAD

**Issue by Priscila343** [EEST1Chivilcoy/BomberosVoluntariosChivilcoy#124]
## Descripción:
Se preguntan datos innecesarios 

## Pasos para reproducir:
- Ingresar a la página de "Bomberos Voluntarios Chivilcoy".
- Ingresar en la sección "Salidas".

## Comportamiento esperado:
- Los datos deben ser relevantes durante la carga 

## Comportamiento actual:
- Se pregunta si el lugar es un departamento en la salidas de incendio comercial, industrial y hospitales/clínicas.

## Capturas de pantalla o registros:
![salida 1](https://github.com/user-attachments/assets/8799d55e-f5c9-46ae-a288-1182b1d83478)
![salida3](https://github.com/user-attachments/assets/847d869e-1a23-40dd-b2a2-a3a6c654daf0)
![salida 7](https://github.com/user-attachments/assets/b8a1658d-3414-4128-ae03-dd834db788f2)

**Comment by Bernard2806** [comment]
Se ha eliminado la pregunta sobre departamentos en las salidas de incendio comercial, industrial y hospitales/clínicas. Los datos ahora son más relevantes para el contexto de cada tipo de salida. Este issue ha sido resuelto.
