### ISSUE TITLE
Cambios en el diseño(Inicio)

### ISSUE THREAD

**Issue by Priscila343** [EEST1Chivilcoy/BomberosVoluntariosChivilcoy#127]
## Descripción:
El inicio de la página no cumple con las expectativas.

## Pasos para reproducir:
- Ingresar a la página de "Bomberos Voluntarios Chivilcoy".

## Comportamiento esperado:
- se necesita realizar un cambio en el inicio de la página.

## Comportamiento actual:
- En el inicio se encuentra la imagen de unos bomberos la cual debe ser eliminada y se debe colocar un fondo de pantalla que es negro, por lo tanto se debe modificar el apartado de unidades

## Capturas de pantalla o registros:
![inicio](https://github.com/user-attachments/assets/3d5ac477-3b8d-47af-bb23-5b6f2a29a007)

**Comment by Valentina-jaime** [comment]
El cliente propuso un cambio en el diseño del inicio y luego cambio de parecer, asi que se reestablecio el diseño anterior
