### ISSUE TITLE
Modificación (Personal)  

### ISSUE THREAD

**Issue by Priscila343** [EEST1Chivilcoy/BomberosVoluntariosChivilcoy#132]
## Descripción:
Se debe modificar el numero relacionado con el cargo de bombero

## Pasos para reproducir:
- Ingresar a la página de "Bomberos Voluntarios Chivilcoy".
- Ingresar en la sección "Personal" .

## Comportamiento esperado:
- los datos de los bomberos deben tener números al utilizarse en los cargos de los bomberos 
- Ejemplo:1°,2°,3°,etc.  

## Comportamiento actual:
- Actualmente los cargos de los bomberos se encuentran con palabras.

## Capturas de pantalla o registros:
![personal](https://github.com/user-attachments/assets/e2c6c8d1-250c-47c9-96ee-3e6960ace697)

**Comment by Bernard2806** [comment]
Se ha implementado la modificación solicitada en el issue. Ahora, los cargos de los bomberos se presentan en formato numérico (1°, 2°, 3°, etc.) en la sección “Personal”. También se eliminaron algunos filtros en la tabla, por lo que es importante verificar si esto afecta la funcionalidad de los filtros existentes.
