### ISSUE TITLE
Se debe crear el apartado de Colocación de Driza

### ISSUE THREAD

**Issue by Priscila343** [EEST1Chivilcoy/BomberosVoluntariosChivilcoy#140]
## Descripción:
El apartado de colocación de Driza en la página se encuentra ausente. 

## Pasos para reproducir:
- Ingresar a la página de "Bomberos Voluntarios Chivilcoy".

## Comportamiento esperado:
- Es necesario que todas las salidas se encuentren en la página.

## Comportamiento actual:
- La salida de colocación de Driza no se encuentra en la página.

## Extra:
_La salida cuenta con los siguientes datos_:
- Datos principales.
- Datos del solicitante.
- Datos del recepcionista.
- Seguro del lugar.
- Datos del chofer.
- Cuerpo participante.
- Datos generales: Tipo de lugar, Nombre del establecimiento, Tipo de servicio, Detalles.

**Comment by Bernard2806** [comment]
Tengo una duda respecto a la creación de esta salida.

Según lo que investigué:

``` 
La “Colocación de Driza” se refiere a la instalación de una cuerda o cabo en un sistema de poleas, generalmente en el contexto de equipos de bomberos. En Argentina, este término se utiliza en el ámbito de los bomberos para describir la instalación de líneas de vida o cuerdas de seguridad que se utilizan en operaciones de rescate y combate de incendios. 
```

En ese caso, ¿no sería una salida en sí misma, sino más bien una acción aplicada en rescates de personas o en incendios?
