### ISSUE TITLE
Implementar restricción de visualización de unidades por bombero en la sección de Firmas

### ISSUE THREAD

**Issue by Priscila343** [EEST1Chivilcoy/BomberosVoluntariosChivilcoy#149]
## Descripción:
En la sección de "Firmas" de la página "Bomberos Voluntarios Chivilcoy", cada bombero debería ver únicamente la unidad de la que está a cargo. Actualmente, esta funcionalidad no está implementada, permitiendo que cualquier bombero pueda ver todas las unidades. Además, es necesario ajustar el calendario para que las limpiezas se registren correctamente con fecha y hora.

## Pasos para reproducir:
1. Ingresar a la página web de "Bomberos Voluntarios Chivilcoy".
2. Navegar al apartado de "Firmas".
3. Observar que todos los bomberos pueden ver las unidades sin restricciones.

## Comportamiento esperado:
- Cada bombero debe poder ver solo la unidad que tiene asignada.
- El calendario debe permitir seleccionar únicamente la fecha y hora de limpieza correspondiente al día actual, sin posibilidad de elegir fechas anteriores.

## Comportamiento actual:
- Cualquier bombero puede ver todas las unidades, sin restricción.
- El calendario no está configurado correctamente para la selección de la fecha de limpieza.

## Recursos visuales:
![firma1](https://github.com/user-attachments/assets/26fbd65a-45b6-43ea-bcfd-1522ce268beb)

## Información adicional:
- Modificar el calendario para que permita seleccionar únicamente el día de limpieza actual con la hora, y no permita elegir fechas anteriores.

**Comment by Bernard2806** [comment]
Es importante mencionar que actualmente no existe un sistema de cuentas o identificación de usuarios, por lo que la funcionalidad que restringiría la visualización de unidades según el bombero asignado todavía no puede implementarse. Para lograr esto, primero es necesario que se implemente un sistema que permita identificar a cada bombero al iniciar sesión, esto se va a realizar por Entra ID (Microsoft). Hasta que esto esté en su lugar, todos los bomberos seguirán teniendo acceso a la visualización de todas las unidades.
