### ISSUE TITLE
Crear Salidas de rescates

### ISSUE THREAD

**Issue by Fefo7** [EEST1Chivilcoy/BomberosVoluntariosChivilcoy#15]

**Comment by Fefo7** [comment]
ya hice las de rescate animal y persona, me falta solo la de ambulancias

**Comment by Bernard2806** [comment]
Falta ajustar esta funcionalidad para que mantenga la coherencia en el estilo con las demás salidas. El modelo ya está desarrollado, pero es necesario alinearlo con el formato utilizado en las otras secciones.
