### ISSUE TITLE
Corrección de error en varias salidas 

### ISSUE THREAD

**Issue by Priscila343** [EEST1Chivilcoy/BomberosVoluntariosChivilcoy#152]
## Descripción:
Se debe modificar varias de las salidas para poder utilizarlas correctamente

## Pasos para reproducir:
- Ingresar a la página de "Bomberos Voluntarios Chivilcoy".
- Ingresar en la sección Salidas y seleccionar una salida.
- cargar con normalidad la salida.

## Comportamiento esperado:
- Todos los datos deben poder ser visualizados de manera correcta y deben poder completarse.

## Comportamiento actual:
- Actualmente en el apartado de carga de Cuerpo participante al momento de cargarlos no se puede visualizar ni completar los apartados de Quien llenó la planilla y el encargado ya que los botones se superponen sobre los otros datos.

## Capturas de pantalla o registros:
![suministro de agua](https://github.com/user-attachments/assets/03660956-669b-434e-804e-b7fb00c1bc0c)
![servicio capacitacion](https://github.com/user-attachments/assets/5ec20a42-5df7-48bd-8543-4877778bd629)

## Extra:
Las siguientes salidas son las que deben ser modificadas
- Suministro de agua
- Servicio de representación
- Salida rescate animal
- Rescate persona
- Factores climáticos
- Incendio viviendas
- Incendio establecimiento público
- Incendio hospital
- Falsa alarma
- Servicio de prevención
- servicio de capacitación
- Retirado de óbito

**Comment by EzeMJaime** [comment]
Este error ya fue corregido en el issus #151, que en el mismo modifique todas las salidas para que no sucediera este error.
