### ISSUE TITLE
Ajustar el diseño en la sección de Detalles de Unidades para evitar desbordes de la patente

### ISSUE THREAD

**Issue by Priscila343** [EEST1Chivilcoy/BomberosVoluntariosChivilcoy#159]
## Descripción:
En la sección de "Detalles" dentro del apartado de Unidades en la página "Bomberos Voluntarios Chivilcoy", la patente de los vehículos sobresale del recuadro, afectando la apariencia y usabilidad de la interfaz. Se debe corregir este problema para mejorar la presentación y hacer la interfaz más amigable para el usuario.

## Pasos para reproducir:
1. Ingresar a la página web de "Bomberos Voluntarios Chivilcoy".
2. Navegar al apartado de "Unidades".
3. Seleccionar la opción "Detalles" de alguna unidad y observar el campo de la patente.

## Comportamiento esperado:
- La patente debe ajustarse correctamente dentro del recuadro sin sobresalir, asegurando una interfaz limpia y amigable para el usuario.

## Comportamiento actual:
- El campo de la patente sobresale del recuadro, afectando la estética y la usabilidad de la sección.

## Recursos visuales:
![image](https://github.com/user-attachments/assets/3c033f60-718f-4bc6-89e8-d3a2dc7a5c19)  
![image](https://github.com/user-attachments/assets/ffbadbb8-01a3-4e37-af48-5f33b52b992c)

**Comment by EzeMJaime** [comment]
También reemplace el icono del botón para dar de baja a un móvil, por otro icono con forma de papelera, esto para que sea mas amigable y visible para el usuario.
