### ISSUE TITLE
Error Visual en Botones de la Salida de Establecimiento Educativo

### ISSUE THREAD

**Issue by Priscila343** [EEST1Chivilcoy/BomberosVoluntariosChivilcoy#164]
## Descripción:
Se presenta un error visual en la salida de "Establecimiento Educativo", donde los botones están mal ubicados.

## Pasos para reproducir:
1. Acceder a la página de "Bomberos Voluntarios Chivilcoy".
2. Seleccionar la salida de "Establecimiento Educativo".
3. Observar la ubicación de los botones al cargar la salida.

## Comportamiento esperado:
- Los botones deberían estar situados debajo del registro, igual que en las demás salidas.

## Comportamiento actual:
- Actualmente, los botones están ubicados al costado, lo que no coincide con el formato de las otras salidas.

## Capturas de pantalla o registros:
![image](https://github.com/user-attachments/assets/a7cf7e7c-a96d-4b2f-8153-0d303523051e)  
![image](https://github.com/user-attachments/assets/4adda3d7-6051-46c1-830f-85a94edcb02c)

**Comment by Bernard2806** [comment]
Este problema ya fue solucionado en el commit mencionado en este issue. Me di cuenta de que ya estaba resuelto, pero decidí mejorar la redacción para mayor claridad.
