### ISSUE TITLE
Error Visual en Botones de la Salida de Colaboración con Fuerzas de Seguridad

### ISSUE THREAD

**Issue by Priscila343** [EEST1Chivilcoy/BomberosVoluntariosChivilcoy#165]
## Descripción:
Se presenta un error visual en la salida de "Colaboración con Fuerzas de Seguridad", donde los botones están mal ubicados.

## Pasos para reproducir:
1. Acceder a la página de "Bomberos Voluntarios Chivilcoy".
2. Seleccionar la salida de "Colaboración con Fuerzas de Seguridad".
3. Observar la ubicación de los botones al cargar la salida.

## Comportamiento esperado:
- Los botones deberían estar situados debajo del registro, igual que en las demás salidas.

## Comportamiento actual:
- Actualmente, los botones están ubicados al costado, lo que no coincide con el formato de las otras salidas.

## Capturas de pantalla o registros:
![image](https://github.com/user-attachments/assets/ada242aa-96f7-4223-8679-74d9d995986c)
![image](https://github.com/user-attachments/assets/4b0fc404-f087-44c1-a958-03f0131f7c56)

**Comment by Bernard2806** [comment]
Este problema ya fue solucionado en el commit mencionado en este issue. Sin embargo, la redacción original no era clara, así que decidí modificarla, aunque ya estaba resuelto y no me di cuenta de eso.
