### ISSUE TITLE
Agregar tipo de Animal

### ISSUE THREAD

**Issue by MaximoGLopez** [EEST1Chivilcoy/BomberosVoluntariosChivilcoy#171]
## Descripción

En la parte de rescates, cuando se selecciona un "Animal" debería darte la opción de seleccionar que tipo de animal era. Por ejemplo:

- Canino
- Felino
- Reptil
- Ave
- Otros

**Comment by Bernard2806** [comment]
La idea está buena, pero el agregar el tipo de animal no es un dato imprescindible para los objetivos de la salida y, por ahora, no es una prioridad.
