### ISSUE TITLE
Módulo Personal: Corrección en la Separación de Palabras

### ISSUE THREAD

**Issue by Agustinrossii29** [EEST1Chivilcoy/BomberosVoluntariosChivilcoy#190]
Ajustar la separación de palabras para que "Cuerpo Activo" se muestre correctamente como dos palabras separadas en el módulo de personal.

![image](https://github.com/user-attachments/assets/f3a36bda-45ea-451e-90b1-2383dabfc5b9)

**Comment by Bernard2806** [comment]
¿No es un poco inecesario tener el estado 'Cuerpo Activo'? Ya se filtra arriba, por lo que no parece necesario mostrarlo de manera separada. Tal vez podríamos simplificar esto.
