### ISSUE TITLE
Modelo en la bdd de limpieza

### ISSUE THREAD

**Issue by Fefo7** [EEST1Chivilcoy/BomberosVoluntariosChivilcoy#72]

**Comment by Fefo7** [comment]
Crear el modelo de datos para poder hacer la parte de limpieza, ya que para poder hacer los puntajes es necesario poder evaluar las limpiezas de cada bombero, a varios bomberos se le asigna un móvil el cual va a limpiar varias veces, mientras este limpiando ese móvil no puede limpiar otro. una ves terminado puede ser asignado a otro móvil.  
Modelo planteado
![Image](https://github.com/EEST1Chivilcoy/BomberosVoluntariosChivilcoy/assets/111016985/84575a6e-ea68-4ff7-9e05-bc8144c4d774)

**Comment by Bernard2806** [comment]
Cierro este issue. Es necesario revisar todo, ya que la limpieza forma parte del módulo de firmas que está siendo propuesto por @OrihuelaConde. Queda pendiente su respuesta para avanzar con el desarrollo del módulo de firmas una vez que se realicen los modelos correspondientes o se presente un planteamiento de los mismos.
