### ISSUE TITLE
Arreglar la tabla de Brigadas

### ISSUE THREAD

**Issue by OrihuelaConde** [EEST1Chivilcoy/BomberosVoluntariosChivilcoy#73]
Revisar todo el funcionamiento de Brigadas y rehacer todo lo que haga falta.

**Comment by Bernard2806** [comment]
Se ha completado la revisión y corrección del funcionamiento de las Brigadas. La tabla ha sido arreglada y se han implementado las mejoras necesarias en la gestión de brigadas.

Solo queda pendiente la funcionalidad de eliminar un bombero de una brigada, que será tratada en un próximo commit o issue. Con esto, cierro este issue.
