### ISSUE TITLE
Cambiar la obligatoriedad de los Campos al cargar un Móvil

### ISSUE THREAD

**Issue by Bernard2806** [EEST1Chivilcoy/BomberosVoluntariosChivilcoy#80]
- Descripción: Actualmente, al cargar un móvil en nuestra aplicación, algunos campos están configurados como obligatorios. Necesitamos ajustar la configuración para que ciertos campos ya no sean obligatorios.

---

Pasos para resolver el problema:

1 - Identificar los campos que deben cambiar su obligatoriedad: Revisa el formulario de carga de móvil y anota los campos que ya no deben ser obligatorios.

2 - Modificar la configuración de los campos en el componente del formulario: Localiza el componente del formulario donde se definen los campos y sus validaciones.

3 - Actualizar las validaciones de los campos: Para cada campo que deba cambiar su obligatoriedad, actualiza la configuración de validación para que ya no sea obligatorio.

4 - Actualizar el modelo de datos si es necesario

5 - Probar los cambios: Probar la aplicación después de realizar los cambios para confirmar que los campos ahora se comporten según lo esperado y que no se generen errores de validación inesperados.

---

Consideraciones adicionales: 
- Documentar los cambios en la validación de los campos en un comentario del issue.

**Comment by IgnGom06** [comment]
Commit relacionado: 0357bfcfbd123666572092161cca734bb0b90ebc
