### ISSUE TITLE
Error en la carga de salida de un móvil 

### ISSUE THREAD

**Issue by abril-aguiar** [EEST1Chivilcoy/BomberosVoluntariosChivilcoy#85]
## Descripción:
Al querer cargar un móvil, para una salida de rescate, la página se congela y no permite interactuar con nada

## Pasos para reproducir:
1- Ingresar a la página de Bomberos Chivilcoy.
2- En la sección "Salidas" seleccionar "Rescate" y el tipo de rescate.
3- Llenar la tabla normalmente hasta llegar a la parte para cargar un móvil.

## Comportamiento esperado:
La página debería permitir seleccionar un móvil.

## Comportamiento actual:
La página se congela y no queda más opción que reiniciarla

## Capturas de pantalla o registros:
![error1](https://github.com/EEST1Chivilcoy/BomberosVoluntariosChivilcoy/assets/173688050/d4aedab6-38db-4b87-a87c-9d3c1a02626b)

## Información del entorno:
- Sistema operativo: Windows 10.
-  Navegador: Chrome Versión 126.0.6478.127 (Build oficial) (64 bits).

**Comment by IgnGom06** [comment]
Bug solucionado antiguamente
