### ISSUE TITLE
Error al editar bomberos

### ISSUE THREAD

**Issue by abril-aguiar** [EEST1Chivilcoy/BomberosVoluntariosChivilcoy#86]
## Descripción:
Al querer editar los datos de un bombero, los nuevos datos no se guardan y la pantalla se congela.

## Pasos para reproducir:
1- Ingresar a la página de Bomberos Chivilcoy.
2- En la sección "Bomberos" y seleccionar "Activos".
3- Hacer click en el botón desplegable "Acciones" y luego "Editar".
4- Cambiar cualquier dato y "Aceptar".

## Comportamiento esperado:
La página debería guardar los cambios en la información del bombero.

## Comportamiento actual:
Los datos no se guardan, la página se congela y no queda más opción que reiniciarla

## Capturas de pantalla o registros:
![error editar bombero](https://github.com/EEST1Chivilcoy/BomberosVoluntariosChivilcoy/assets/173688050/b3a315d6-342d-4fbf-a6b4-ce80468b1cb7)

## Información del entorno:
- Sistema operativo: Windows 10.
-  Navegador: Chrome Versión 126.0.6478.127 (Build oficial) (64 bits).

**Comment by Bernard2806** [comment]
Arreglado hace tiempo...
