### ISSUE TITLE
Error al agregar sanción

### ISSUE THREAD

**Issue by abril-aguiar** [EEST1Chivilcoy/BomberosVoluntariosChivilcoy#87]
## Descripción:
Al querer agregar una sanción la pantalla se congela.

## Pasos para reproducir:
1- Ingresar a la página de Bomberos Chivilcoy.
2- En la sección "Bomberos" y seleccionar "Activos".
3- Hacer click en el botón "Agregar Sanción".

## Comportamiento esperado:
La página debería mostrar una ventana para poder poner la sanción al bombero seleccionado.

## Comportamiento actual:
La página se congela y no queda más opción que reiniciarla

## Capturas de pantalla o registros:
![error agregar sancion](https://github.com/EEST1Chivilcoy/BomberosVoluntariosChivilcoy/assets/173688050/3e8ff139-30e7-47a8-92bc-73a701abd10f)

## Información del entorno:
- Sistema operativo: Windows 10.
-  Navegador: Chrome Versión 126.0.6478.127 (Build oficial) (64 bits).

**Comment by IgnGom06** [comment]
Actualmente no se encuentran las 
 sanciones para Personal
