### ISSUE TITLE
Datos irrelevantes (Incendios-Establecimiento Educativo)

### ISSUE THREAD

**Issue by abril-aguiar** [EEST1Chivilcoy/BomberosVoluntariosChivilcoy#93]
## Descripción:
datos irrelevantes en la carga de datos.

## Pasos para reproducir:
- Ingresar a la página de "Bomberos Voluntarios Chivilcoy".
- Ingresar en la sección "Salidas" y seleccionar "Incendios" del tipo "Establecimiento Educativo".
- Cargar con normalidad la salida.

## Comportamiento esperado:
los datos cargados deben ser relevantes 

## Comportamiento actual:
pregunta si el establecimiento educativo es un departamento

## Capturas de pantalla o registros:
![establecimiento educativo irrelevante 2024-09-05 103332](https://github.com/user-attachments/assets/602176d8-01d7-44ed-aceb-3c12381a6187)

## Información del entorno:
- Sistema operativo: Windows 10
- Versión del software: v2.0.1
- Navegador: Chrome Versión 126.0.6478.127

**Comment by Bernard2806** [comment]
Se ha corregido el comportamiento que generaba datos irrelevantes al cargar incendios en Establecimientos Educativos. Ahora los datos cargados son los esperados y no se pregunta si el establecimiento educativo es un departamento. Issue cerrado.
