### ISSUE TITLE
Errores en la salida de Materiales Peligrosos

### ISSUE THREAD

**Issue by abril-aguiar** [EEST1Chivilcoy/BomberosVoluntariosChivilcoy#98]
## Descripción:
Hay impedimentos en la carga de la salida. 
Materiales Peligrosos es un ejemplo, esto sucede en todas las salidas. 

## Pasos para reproducir:
- Ingresar a la página de "Bomberos Voluntarios Chivilcoy".
- Ingresar en la sección "Salidas" y seleccionar "Materiales Peligrosos".
- Cargar con normalidad la salida.

## Comportamiento esperado:
- El numero parte debería autoincrementarse de acuerdo a las salidas anteriores.
- Se debería poder imprimir la salida luego de llenarla.

## Comportamiento actual:
- Luego de cargar la última salida de "Materiales Peligrosos" el número parte no se autoincrementa, como si la salida no hubiera cargado.
- Al terminar de llenar una salida y presionar "Imprimir Salida", no hace lo que corresponde, da error y hay que reiniciar la página.

## Capturas de pantalla o registros:

Sin capturas o registros.

## Información del entorno:
- Sistema operativo: Windows 10
- Versión del software: v2.0.1
- Navegador: Chrome Versión 126.0.6478.127

**Comment by Bernard2806** [comment]
Se ha solucionado el problema relacionado con el número de parte en la función del servicio IPartedService, que se encarga de generar el número de parte para cada salida. El problema surgió después de registrar una salida de Materiales Peligrosos, ya que el año de salida no se estaba guardando correctamente.

La corrección se realizó en el commit 1fc6f59b1bafba01af700eb6761dab7ff8426723, donde se ajustó el código para asegurar que el año de la salida se guarde adecuadamente y se refleje en el número de parte generado.
