### ISSUE TITLE
Implementación de la API GeoRef AR para Validación y Obtención de Direcciones en las Salidas

### ISSUE THREAD

**Issue by Bernard2806** [EEST1Chivilcoy/BomberosVoluntariosChivilcoy#99]
Estoy considerando la opción de utilizar la API de [Georef AR](https://datosgobar.github.io/georef-ar-api/) para validar direcciones para las salidas. Quiero determinar si esta API puede ser una solución adecuada para nuestra necesidad de validación de direcciones.

Aquí hay un ejemplo de cómo se podría hacer una consulta a la API Georef para validar una dirección “Luis Mohr 127, Chivilcoy, Buenos Aires”:

```
https://apis.datos.gob.ar/georef/api/direcciones?direccion=Luis%20Mohr%20127&localidad=Chivilcoy&provincia=Buenos%20Aires
```

**Comment by OrihuelaConde** [comment]
Comprendo que puede ser algo útil, pero tenemos otras prioridades actualmente.

**Comment by Bernard2806** [comment]
Después de comer, me puse a trabajar en esto por aburrimiento y ya he completado la integración inicial con la API de Georef AR. La implementación se realizó como un select de Ant Design Blazor con la funcionalidad de búsqueda habilitada para colocar el nombre de la Calle en las salidas donde anteriomente se encontraba un input. Ahora, lo único que falta es determinar si esta API es una solución viable. Aunque tenemos otras prioridades en este momento, creo que esta API podría ser útil si cumple con nuestros requisitos. ¿Podemos revisar su viabilidad?

**Comment by Bernard2806** [comment]
### Problema al Implementar la API GeoRef AR

En el proceso de implementar la API de GeoRef AR para validar direcciones en el módulo de Salidas del proyecto, se encontro un problema. Durante las pruebas locales, la API funcionó correctamente. Sin embargo, al desplegar la aplicación en Azure, me encontré con un error **403 Forbidden** al realizar las solicitudes a la API.

### Acciones Tomadas

- Correo a Jefatura de Datos Argentinos: Envie un correo a la Jefatura de Datos Argentinos solicitando asistencia para entender si existe un límite de solicitudes por IP o si hay algun otra restricción que pude estar pasando por alto.
- Creación de un Issue: Cree un issue en el [Repositorio Oficial](https://github.com/datosgobar/georef-ar-api/) de la API solicitando asistencia para resolver el problema.

### Plan de Contingencia

Hasta recibir una respuesta de las autoridades correspondientes, se procederá de la siguiente manera:

- Cambio en el Comportamiento del Label: En caso de que la verificación con la conexión de la API falle, se reemplazará el Label implementado con las sugerencias de las calles por un simple input en el formulario, permitiendo la entrada manual de las direcciones.

### Estado
Estoy a la espera de una respuesta por parte de la Jefatura de Datos Argentinos o de los mantenedores de la API para poder continuar con la integración. Así que de momento no se seguirá trabajando en esto.

**Comment by Bernard2806** [comment]
Parece que después de varios intentos y correcciones, el error con la API GeoRef AR se solucionó en el commit c108b94a3b308c8e6563d1435cd3fa8c114ea1f6. Gracias a esta corrección, ahora la implementación básica de la API está funcional, permitiendo obtener los nombres de las calles en el módulo de Salidas. Debido a la proximidad de la fecha límite para la presentación del 3 de septiembre, por ahora se mantendrá así, centrándose únicamente en la obtención de los nombres de las calles. Cualquier funcionalidad adicional o mejora se considerará en futuras iteraciones.
